FROM node:14

LABEL maintainer "Informatie Vlaanderen <informatievlaanderen@vlaanderen.be>"

COPY / /app
WORKDIR /app

# RUN npm install
# If you are building your code for production
RUN npm ci

RUN npm run build

CMD [ "node", "lib/api.js" ]
