version: "3.8"

services:
  api:
    build: .
    container_name: base-registries-api
    hostname: base-registries-api
    environment:
      DB_USER: postgres
      DB_PASSWORD: dev
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: base_registries
      DOMAIN_NAME: xxx
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db
    command: [ "node", "lib/api.js" ]

  fetcher:
    build: .
    container_name: base-registries-fetcher
    hostname: base-registries-fetcher
    environment:
      DB_USER: postgres
      DB_PASSWORD: dev
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: base_registries
      API_KEY: xxx
    depends_on:
      - db
    links:
      - db
    command: [ "node", "lib/fetcher.js" ]

  db:
    build: ./database
    container_name: base-registries-db
    hostname: base-registries-db
    restart: always
    environment:
      POSTGRES_DB: base_registries
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev
    ports:
      - 5432:5432

  dba:
    image: dpage/pgadmin4:5.7
    container_name: base-registries-dba
    hostname: base-registries-dba
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@dev.be
      PGADMIN_DEFAULT_PASSWORD: dev
    ports:
      - 8001:80
    depends_on:
      - db
    links:
      - db
  loadbalancer:
    container_name: base-registries-nginx
    build: ./nginx
    tty: true
    links:
      - api
    ports:
    - 80:80
