version: "3.8"

services:
  db:
    image: postgres
    container_name: base_registries_db
    hostname: base_registries_db
    restart: always
    environment:
      POSTGRES_DB: base_registries
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    ports:
      - 5432:5432
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/01-init_db.sql
      - ./projection_status.sql:/docker-entrypoint-initdb.d/02-projection_status.sql
      - ./municipalities.sql:/docker-entrypoint-initdb.d/03-municipalities.sql
      - ./postal_information.sql:/docker-entrypoint-initdb.d/04-postal_information.sql
      - ./street_names.sql:/docker-entrypoint-initdb.d/05-street_names.sql
      - ./addresses.sql:/docker-entrypoint-initdb.d/06-addresses.sql
      - ./address_municipality.sql:/docker-entrypoint-initdb.d/07-address_municipality.sql
      - ./address_streetname.sql:/docker-entrypoint-initdb.d/08-address_streetname.sql

  dba:
    image: dpage/pgadmin4:5.6
    container_name: base_registries_dba
    hostname: base_registries_dba
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@dev.be
      PGADMIN_DEFAULT_PASSWORD: dev
    ports:
      - 8001:80
    networks:
      - db
