# Use the standard Nginx image from Docker Hub
FROM nginx
# The Dockerfile's author
LABEL BASE_REGISTRIES
# Copy the configuration file from the current directory and paste
# it inside the container to use it as Nginx's default config.
COPY nginx.conf /etc/nginx/nginx.conf
# Port 5000 of the container will be exposed and then mapped to port
# 5000 of our host machine via Compose. This way we'll be able to
# access the server via localhost:5000 on our host.
EXPOSE 5000

# Start Nginx when the container has provisioned.
CMD ["nginx", "-g", "daemon off;"]
